apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jl24
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jl24
    app.kubernetes.io/part-of: load-app-f716d1f7-336c-4516-b2dd-e2123913f7e9
  name: devfile-sample-jl24
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-jl24
status:
  loadBalancer: {}
